[colors.primary]
background = '#141310'
foreground = '#e6e2db'
 
[colors.cursor]
text = '#e6e2db'
cursor = '#cbc6b7' 
 
[colors.vi_mode_cursor]
text = '#141310'
cursor = '#cfc88f' 
 
[colors.search.matches]
foreground = '#49473b' 
background = '#b2cfa7' 
 
[colors.search.focused_match]
foreground = '#49473b' 
background = '#cfc88f' 
 
[colors.footer_bar]
foreground = '#49473b' 
background = '#e6e2db' 
 
[colors.hints.start]
foreground = '#49473b' 
background = '#ccc7ac' 
 
[colors.hints.end]
foreground = '#49473b' 
background = '#ccc7ac' 
 
[colors.selection]
text = '#141310'
background = '#cfc88f'
 
 
[colors.normal]
black = '#181818' 
red = '#ffb4ab' 
green = '#cfc88f' 
yellow = '#646030' 
blue = '#cfc88f' 
magenta = '#b2cfa7' 
cyan = '#ccc7ac' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 