[colors.primary]
background = '#141312'
foreground = '#e6e2e0'
 
[colors.cursor]
text = '#e6e2e0'
cursor = '#cac6bc' 
 
[colors.vi_mode_cursor]
text = '#141312'
cursor = '#cac6b8' 
 
[colors.search.matches]
foreground = '#48473f' 
background = '#c3c8bf' 
 
[colors.search.focused_match]
foreground = '#48473f' 
background = '#cac6b8' 
 
[colors.footer_bar]
foreground = '#48473f' 
background = '#e6e2e0' 
 
[colors.hints.start]
foreground = '#48473f' 
background = '#cac6bf' 
 
[colors.hints.end]
foreground = '#48473f' 
background = '#cac6bf' 
 
[colors.selection]
text = '#141312'
background = '#cac6b8'
 
 
[colors.normal]
black = '#181818' 
red = '#ffb4ab' 
green = '#cac6b8' 
yellow = '#615f53' 
blue = '#cac6b8' 
magenta = '#c3c8bf' 
cyan = '#cac6bf' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 