[colors.primary]
background = '#141316'
foreground = '#e6e1e6'
 
[colors.cursor]
text = '#e6e1e6'
cursor = '#cbc4cf' 
 
[colors.vi_mode_cursor]
text = '#141316'
cursor = '#d4bbff' 
 
[colors.search.matches]
foreground = '#49454e' 
background = '#f1b7c4' 
 
[colors.search.focused_match]
foreground = '#49454e' 
background = '#d4bbff' 
 
[colors.footer_bar]
foreground = '#49454e' 
background = '#e6e1e6' 
 
[colors.hints.start]
foreground = '#49454e' 
background = '#cdc2db' 
 
[colors.hints.end]
foreground = '#49454e' 
background = '#cdc2db' 
 
[colors.selection]
text = '#141316'
background = '#d4bbff'
 
 
[colors.normal]
black = '#181818' 
red = '#ffb4ab' 
green = '#d4bbff' 
yellow = '#6c4ea2' 
blue = '#d4bbff' 
magenta = '#f1b7c4' 
cyan = '#cdc2db' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 